

import time
import asyncio
import requests
from datetime import datetime
from scrape_combined_crawl4ai import process_urls, carregar_sem_dados_url
import re

async def run_combined_crawler():
    print(f'Executando scrape_combined_crawl4ai.py às {datetime.now()}')
    try:
        combined_urls = [
            "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-shampoo-1-litro/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-condicionador-1-litro/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-mascara-capilar-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-shampoo-1-litro/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-condicionador-1-litro/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-mascara-capilar-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-luminous-reveal-shampoo-1-litro/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-luminous-reboost-mascara-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-oleo-capilar-100ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-light-oleo-capilar-100ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-tratamento-60ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/kit-cadiveu-professional-plastica-dos-fios-alinhamento-profissional-3-produtos/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-gradual-smoothing-mist-spray-protetor-termico-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-by-boca-rosa-hair-oleo-capilar-quartzo-liquido-65ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-one-condition-condicionador-355ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-mascara-capilar-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-heaven-in-hair-mascara-capilar-250g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-supercream-creme-modelador-250g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-leavein-protetor-termico-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-inner-restore-intensif-mascara-capilar-de-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-inner-restore-mascara-capilar-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-inner-restore-deep-moisturizing-conditioner-mascara-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-cpr-step-3-condicionador-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-condicionando-a-juba-hidronutritivo-condicionador-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-ondulando-a-juba-creme-de-pentear-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-modelando-a-juba-geleia-seladora-300g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-encrespando-a-juba-creme-de-pentear-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-juba-mascara-capilar-500g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/joico-moisture-recovery-moisturizing-smart-release-shampoo-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/joico-kpak-to-repair-damage-hair-smart-release-shampoo-300ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-supercream-creme-modelador-500g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-one-condition-decadence-condicionador-355ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-proteina-condicionante-preshampoo-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-profissional-glamour-essentials-serum-capilar-65ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-leavein-nutritivo-215ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-glamour-essentials-fluido-condicionante-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/kit-cadiveu-professional-essentials-hair-remedy-home-care-3-produtos/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-shampoo-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-tratamento-60ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-acai-110ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-encrespando-a-juba-creme-de-pentear-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-cabeleira-crescimento-e-fortalecimento-fluido-fortificante-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/kit-homecare-cadiveu-essentials-quartzo-shine-2-produtos/ofertas-marketplace",
            "https://www.belezanaweb.com.br/kit-cadiveu-professional-plastica-dos-fios-alinhamento-profissional-3-produtos/ofertas-marketplace",
            "https://www.belezanaweb.com.br/kit-homecare-cadiveu-essentials-quartzo-shine-2-produtos/ofertas-marketplace",
            "https://www.belezanaweb.com.br/aneethun-linha-a-mascara-capilar-500g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-styling-cream-creme-modelador-500g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-divine-antifrizz-condicionador-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-silk-moisture-condicionador-240ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-essentials-maxi-ondas-leavein-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-warming-express-mascara-de-nutricao-150ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-shampoo-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-angell-leave-in-355ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-mascara-reparadora-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-mascara-de-tratamento-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-no-poo-shampoo-cremoso-355ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-heaven-in-hair-mascara-capilar-500g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/aneethun-linha-a-silicone-com-tutano-e-queratina-creme-capilar-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-original-shampoo-nopoo-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-balm-leavein-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-leavein-150ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-low-poo-deligh-shampoo-355ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-no-poo-decadence-shampoo-sem-espuma-355ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-stages-nutrition-shampoo-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-one-condition-delight-condicionador-355ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-essential-power-dose-ampola-de-tratamento-capilar-13ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-leavein-reparador-215ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-sem-sulfato-shampoo-reparador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-care-angell-modelador-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/widi-care-blend-de-oleos-vegetais-tratamento-capilar-60ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-angell-leavein-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-condicionador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-go-curly-leavein-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-shampoo-shampoo-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/kit-cadiveu-professional-glamour-essentials-home-care-2-produtos/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-condicionador-reparador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-go-curly-mascara-capilar-200g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/prohall-cosmetic-btx-blend-repair-tratamento-disciplinante-300g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-divine-antifrizz-shampoo-1000ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-stages-treatment-leavein-multifuncional-em-spray-260ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/joico-moisture-recovery-smart-release-condicionador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-stage-hydration-mascara-capilar-200g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-mask-mascara-capilar-condicionadora-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-essentials-bye-bye-frizz-killer-leave-in-120ml",
            "https://www.belezanaweb.com.br/cadiveu-professional-glamour-essentials-mascara-capilar-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-condicionador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-inner-restore-intensif-mascara-capilar-de-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-shampoo-low-poo-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-divine-condicionador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-conditioner-condicionador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/aneethun-linha-a-shampoo-300ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-styling-cream-creme-de-pentear-250g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/jacques-janine-professionnel-bb-cream-finalizador-240ml",
            "https://www.belezanaweb.com.br/jacques-janine-professionnel-liso-absoluto-fluido-termoativado-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-bond-angel-blonde-repair-mascara-capilar-200g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-essentials-hair-remedy-leavein-condicionante-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/joico-kpak-to-repair-damage-hair-smart-release-condicionador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-beach-hair-day-finalizador-capilar-260ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-delight-shampoo-low-poo-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-bond-angel-thermal-blond-leavein-matizador-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-stagesnutrition-condicionador-250-ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/kit-cadiveu-professional-plastica-dos-fios-2-produtos/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-essential-fluido-reparador-leavein-60ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-one-condition-decadence-condicionador-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/aneethun-repair-system-mascara-posquimica-250g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-revival-condicionador-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-decadence-shampoo-no-poo-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-shampoo-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-fiber-mask-efeito-teia-mascara-capilar-500g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-glamour-essentials-shampoo-250ml",
            "https://www.belezanaweb.com.br/brae-divine-home-care-mascara-capilar-200g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-fusion-shampoo-1000ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-fusion-condicionador-1-litro/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-fusion-mascara-reparadora-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-inner-restore-mascara-capilar-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-cpr-step-0-shampoo-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-silk-moisture-shampoo-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-silk-moisture-shampoo-280ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-inner-restore-intensif-mascara-capilar-de-500ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-balance-condicionador-240ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-true-hue-color-serum-capilar-55ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-balance-shampoo-280ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-smooth-shampoo-1000ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-silk-moisture-condicionador-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-fiber-mask-efeito-teia-mascara-capilar-500g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-revival-condicionador-1l",
            "https://www.belezanaweb.com.br/brae-soul-color-condicionador-1litro/ofertas-marketplace",
            "https://www.belezanaweb.com.br/joico-joifull-volumizing-smart-release-leavein-100ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/wella-professionals-color-motion-condicionador-1000ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/joico-blonde-life-brilliant-glow-brightening-oil-oleo-capilar-100ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/mp293269-mascara-cabelos-loiros-brae-stages-blonding-200g/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-shampoo-stages-blonding-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/mp293272-mascara-cabelos-coloridos-brae-stages-color-protect-200g",
            "https://www.belezanaweb.com.br/brae-stages-colors-protect-shampoo-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/brae-stage-hydration-shampoo-250ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-final-style-extra-shine-spray-de-brilho-150ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-true-hue-shampoo-sem-sulfato-280ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-inner-restore-deep-moisturizing-mascara-de-hidratacao-50ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-true-hue-condicionador-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/senscience-cpr-step-1-porosity-reconstructor-tratamento-reconstrutor1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-blonde-reconstructor-ph-balancing-mask-mascara-capilar-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-soft-sense-condicionador-3l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-hair-remedy-condicionador-980ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-mascara-capilar-980ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-condicionador-980ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-shampoo-980ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-wave-maker-ativador-de-cachos-180ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-mist-er-right-finalizador-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-bleave-in-finalizador-condicionante-200ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-b-leavein-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-set-it-free-finalizador-120ml/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-one-condition-delight-condicionador-1l/ofertas-marketplace",
            "https://www.belezanaweb.com.br/deva-curl-low-poo-shampoo-355ml/ofertas-marketplace",
        ]
        
        await process_urls(combined_urls)
    except Exception as e:
        print(f'Erro ao executar scrape_combined_crawl4ai.py: {e}')

if __name__ == '__main__':
    asyncio.run(run_combined_crawler())


